# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "BackendReservasDatabase"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysql --user=$$root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
      timeout: 20s
      retries: 10
  backendreservasapi:
    image: backendreservasapi
    build:
      context: .
      dockerfile: BackendReservas.Api/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      database:
        condition: service_healthy